### PR TITLE
Prost 2 nerfed

### PR DESCRIPTION
**Pull request by nerfed**
Changed Eid, spaces, altitude to better fit and double quotes

### CODE REVIEW

**Comment by ashellum** [comment]
Not sure what's up with the thing on the end, but I think it's still good.

**Comment by nerfed** [comment]
@ashellum  Yea I just noticed that too . No idea either.

**Comment by dlennox24** [comment]
@ashellum @nerfed That just means that there isn't a blank new line at the end of the file.

**Comment by nerfed** [comment]
@dlennox24 cool thanks man!

**Pull request merged**
