### PR TITLE
Update brews.csv

### PR DESCRIPTION
**Pull request by bpowley**
Removed the extra quotation marks. 
Closes issue #294

### CODE REVIEW

**Comment by bobfromholland** [comment]
It looks like you have actual quotation marks in the coordinates instead of using primes, I don't know enough about it to approve it or request a change though.

**Comment by bpowley** [comment]
you're correct @bobfromholland and @dlennox24, i think i updated it correctly? please let me know if it's still showing quotation marks/single quotes - i'm not sure if i have to create a new pull request or simply adding new commits will do.

**Comment by dlennox24** [comment]
Pushing new commits to the `bpowley-patch` branch will automatically update this PR. That's what those little things that look like a circle with a line on either side are.

**Comment by bpowley** [comment]
@dlennox24 sweet, thanks!

**Pull request merged**
