### PR TITLE
Add boggy draw

### PR DESCRIPTION
**Pull request by lsouth**
Fixed latitude and longitude formats.

### CODE REVIEW

**Comment by kelseycribari** [comment]
Looks good to me!

**Comment by ekdoan** [comment]
I would remove the spaces before the data. He mentioned that wasn't a good idea. Also, I'm not sure if the negative is needed.

**Comment by lsouth** [comment]
Fixed spaces issue -- @ekdoan

**Comment by schulzecb** [comment]
It looks good to me! I'll go ahead and merge this.

**Pull request merged**
