### PR TITLE
Update hullings line

### PR DESCRIPTION
**Pull request by joshhullings**
updated the coordinates to be correct format

### CODE REVIEW

**Comment by dlaw08** [comment]
looks good, nice

**Comment by joshhullings** [comment]
I didn't touch line 1 at all, I don't know why it claims I edited it.

**Comment by dlennox24** [comment]
Out of curiosity, what text editor did you use? How did you create the commit?

**Comment by joshhullings** [comment]
I opened it using notepad on my laptop and just edited my line. I committed it and pushed the branch through git, then created the pull request on github

**Comment by joshhullings** [comment]
I just don't know how to fix it since when I look at it line 1 is identical in both.

**Comment by dlennox24** [comment]
Interesting. Notepad added it. I don't know what "it" is because it doesn't even show up as an invisible character in Atom. I'll go ahead and approve this since it's not changing anything or adding any unnecessary characters. I think the only way to fix it would be to roll back your commit on your branch and edit it with another file or use a Git client like SourceTree where you can stage and commit only specific lines.

**Comment by joshhullings** [comment]
I'll have to look into that for the future. Thanks for taking the time!

**Pull request merged**
